name       : perl-datetime
version    : '1.45'
release    : 2
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-1.45.tar.gz : fde87438a888b95f00916dfbcf0bbcdaf2d60b682d6d55d275f86184651aa9f0
license    : Artistic-2.0
component  : programming.perl
summary    : Date and time functions for Perl scripts
description: |
    Date and time functions for Perl scripts
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
