name       : perl-datetime
version    : 1.42
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-1.42.tar.gz : efa4badf07365d1b03ee5527fc79baaf7d8b449bf7baad13599f04177232416e
license    : Artistic-2.0
component  : programming.perl
summary    : Date and time functions for Perl scripts
description: |
    Date and time functions for Perl scripts
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
