name       : perl-datetime
version    : '1.45'
release    : 3
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/DateTime-1.45.tar.gz : fde87438a888b95f00916dfbcf0bbcdaf2d60b682d6d55d275f86184651aa9f0
license    : Artistic-2.0
component  : programming.perl
summary    : Date and time functions for Perl scripts
description: |
    Date and time functions for Perl scripts
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-cpan-meta-check
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-dist-checkconflicts
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
