name       : perl-datetime
version    : '1.49'
release    : 5
source     :
    - https://github.com/houseabsolute/DateTime.pm/archive/v1.49.tar.gz : 00dab228ce740d09bc8948fe31b6fb2a88d235fbe00330c733f34ab802a987e2
license    : Artistic-2.0
component  : programming.perl
summary    : Date and time functions for Perl scripts
homepage   : https://github.com/houseabsolute/DateTime.pm
description: |
    Date and time functions for Perl scripts
builddeps  :
    - perl-b-hooks-endofscope
    - perl-class-data-inheritable
    - perl-class-singleton
    - perl-cpan-meta-check
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-devel-stacktrace
    - perl-dist-checkconflicts
    - perl-eval-closure
    - perl-exception-class
    - perl-file-sharedir
    - perl-module-implementation
    - perl-mro-compat
    - perl-namespace-autoclean
    - perl-namespace-clean
    - perl-package-stash
    - perl-params-validationcompiler
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-exporter-progressive
    - perl-sub-identify
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
rundeps    :
    - perl-datetime-locale
    - perl-datetime-timezone
    - perl-dist-checkconflicts
    - perl-namespace-autoclean
    - perl-params-validationcompiler
    - perl-specio-exporter
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
